### ISSUE TITLE
[Hacktoberfest] Add more rules to cover more standards

### ISSUE THREAD

**Issue by PatricNox** [fossbarrow/laravel-phpcs#1]
All changes that makes the sniffer more accurate towards Laravel's coding standard is always highly appreciated and welcome.

Please see [CONTRIBUTING](https://github.com/fossbarrow/laravel-phpcs/blob/main/docs/CONTRIBUTING.md) for more details.

**Comment by cfc7-unikent** [comment]
Hi @PatricNox do you know if there is a public list of the Laravel coding standards rules?

**Comment by christiancable** [comment]
Hi @PatricNox do you know if there is a public list of the Laravel coding standards rules?

**Comment by PatricNox** [comment]
@christiancable  Hi!

There's not. By their own words, Laravel is a variant of the PSR-12 standard. 
Best way to pinpoint specific rules is to compare their coding styile within the source code to the PSR-12 standard.
