### ISSUE TITLE
Incorrect tag at line 136

### ISSUE THREAD

**Issue by zepo87** [fossbarrow/laravel-phpcs#5]
Hi! phpcs gives me an error on executing this ruleset at line 136: 

`<file->tests</file>`

The tag is opened as `<file->` I guess that's where the problem lies.

**Comment by PatricNox** [comment]
Hello!

Yes I was too fast on approving this PR: https://github.com/fossbarrow/laravel-phpcs/commit/17c649aba2d5de8707cbecfd7ca3e3c5539cdf4f 

I will update this in due time.

**Comment by PatricNox** [comment]
https://github.com/fossbarrow/laravel-phpcs/commit/f4cc86b88b58b6dd58576ec2965c03778fb54bea
